# Generated by Django 2.2.7 on 2019-11-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191127_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motorcyclead',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scooterad',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
