# Generated by Django 2.2.7 on 2019-12-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='dealer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Dealer'),
        ),
    ]
